// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"encoding/json"
	"fmt"
	"io"
)

const (
	create_9__17 = `<form id="storelocation"><div class="form-group row"><div class="form-group col-sm-12">`
)

func Storelocationcreate(c ViewContainer, wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(index__0)
	WriteAll(c.ProxyPath+"css/bootstrap.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-table.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/select2.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-colorpicker.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/fontawesome.all.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/chimitheque.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/materialdesignicons.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-toggle.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/animate.min.css", true, buffer)
	buffer.WriteString(index__9)
	WriteAll(c.ProxyPath+"js/jquery-3.3.1.min.js", true, buffer)
	buffer.WriteString(index__10)
	WriteAll(c.ProxyPath+"img/logo_chimitheque_small.png", true, buffer)
	buffer.WriteString(index__11)

	if HasPermission(c.PersonID, "r", "products", -2) {
		buffer.WriteString(index__35)
		WriteAll(c.ProxyPath+"v/products", true, buffer)
		buffer.WriteString(index__36)
		WriteAll(T("menu_home", 1), true, buffer)
		buffer.WriteString(index__37)

	}
	if HasPermission(c.PersonID, "r", "products", -2) {
		buffer.WriteString(index__35)
		WriteAll(c.ProxyPath+"v/products?bookmark=true", true, buffer)
		buffer.WriteString(index__39)
		WriteAll(T("menu_bookmark", 1), true, buffer)
		buffer.WriteString(index__37)

	}
	if HasPermission(c.PersonID, "w", "products", -2) {
		buffer.WriteString(index__41)
		WriteAll(c.ProxyPath+"vc/products", true, buffer)
		buffer.WriteString(index__42)
		WriteAll(T("menu_create_productcard", 1), true, buffer)
		buffer.WriteString(index__37)

	}
	if HasPermission(c.PersonID, "r", "entities", -2) {
		buffer.WriteString(index__44)
		WriteAll(T("menu_entity", 1), true, buffer)
		buffer.WriteString(index__45)
		WriteAll(c.ProxyPath+"v/entities", true, buffer)
		buffer.WriteString(index__46)

		if HasPermission(c.PersonID, "all", "all", -1) {
			buffer.WriteString(index__48)
			WriteAll(c.ProxyPath+"vc/entities", true, buffer)
			buffer.WriteString(index__49)

		}
		buffer.WriteString(index__47)

	}
	if HasPermission(c.PersonID, "r", "storages", -2) {
		buffer.WriteString(index__50)
		WriteAll(T("menu_storelocation", 1), true, buffer)
		buffer.WriteString(index__45)
		WriteAll(c.ProxyPath+"v/storelocations", true, buffer)
		buffer.WriteString(index__46)

		if HasPermission(c.PersonID, "all", "all", -2) {
			buffer.WriteString(index__48)
			WriteAll(c.ProxyPath+"vc/storelocations", true, buffer)
			buffer.WriteString(index__49)

		}
		buffer.WriteString(index__47)

	}
	if HasPermission(c.PersonID, "r", "people", -2) {
		buffer.WriteString(index__56)
		WriteAll(T("menu_people", 1), true, buffer)
		buffer.WriteString(index__45)
		WriteAll(c.ProxyPath+"v/people", true, buffer)
		buffer.WriteString(index__46)

		if HasPermission(c.PersonID, "w", "people", -2) {
			buffer.WriteString(index__48)
			WriteAll(c.ProxyPath+"vc/people", true, buffer)
			buffer.WriteString(index__49)

		}
		buffer.WriteString(index__47)

	}
	buffer.WriteString(index__12)
	WriteAll(c.ProxyPath+"vu/peoplepass", true, buffer)
	buffer.WriteString(index__13)
	WriteAll(T("menu_password", 1), true, buffer)
	buffer.WriteString(index__14)
	WriteAll(c.ProxyPath+"delete-token", true, buffer)
	buffer.WriteString(index__15)
	WriteAll(T("menu_logout", 1), true, buffer)
	buffer.WriteString(create__16)

	{
		var (
			iconitem   = "creation"
			iconaction = "docker"
			label      = "create store location"
		)

		buffer.WriteString(index_2__68)
		WriteEscString("mdi-"+iconitem+" mdi mdi-48px", buffer)
		buffer.WriteString(index_2__69)
		WriteEscString("mdi-"+iconaction+" mdi mdi-18px", buffer)
		buffer.WriteString(index_2__70)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__71)

	}

	buffer.WriteString(create_9__17)

	{
		var (
			label = "name"
			name  = "storelocation_name"
		)

		buffer.WriteString(index_2__72)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__73)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__74)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__75)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__77)
	}

	buffer.WriteString(index_8__18)

	{
		var (
			label = "entity"
			name  = "entity"
		)

		buffer.WriteString(index_2__72)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__73)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__86)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__75)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__162)

	}

	buffer.WriteString(index_8__18)

	{
		var (
			label = "parent"
			name  = "storelocation"
		)

		buffer.WriteString(index_2__72)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__73)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__86)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__75)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__162)

	}

	buffer.WriteString(index_8__18)

	{
		var (
			label = "can store?"
			name  = "storelocation_canstore"
		)

		buffer.WriteString(index_4__178)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__179)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__73)
		WriteEscString(label, buffer)
		buffer.WriteString(index_4__181)
	}

	buffer.WriteString(index_8__18)

	{
		var (
			label = "color"
			name  = "storelocation_color"
		)

		buffer.WriteString(index_2__72)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__73)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__74)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__75)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__77)
	}

	buffer.WriteString(index_8__22)
	WriteAll(T("save", 1), true, buffer)
	buffer.WriteString(create__21)

	json, _ := json.Marshal(c)

	var out string
	for key, value := range c.URLValues {
		out += fmt.Sprintf("URLValues.set(%s, %s)\n", key, value)
	}

	buffer.WriteString(index__17)
	WriteAll(c.ProxyPath, false, buffer)
	buffer.WriteString(index__18)
	buffer.WriteString(fmt.Sprintf("%s", json))
	buffer.WriteString(index__19)
	buffer.WriteString(out)
	buffer.WriteString(index__20)
	WriteAll(c.ProxyPath+"js/jquery.formautofill.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/jquery.validate.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/jquery.validate.additional-methods.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/select2.full.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/popper.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap-table.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap-confirmation.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap-colorpicker.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap-toggle.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/JSmol.lite.nojq.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/chim/gjs-common.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/chim/chimcommon.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/chim/login.js", true, buffer)
	buffer.WriteString(index_8__42)

}
