// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"encoding/json"
	"fmt"
	"io"
)

const (
	create__16 = `</span></a></li></ul></div></nav>`
	create__17 = `<form id="entity"><div class="form-group row">`
	create__21 = `</span></button></div><!--  Code generated by go generate; DO NOT EDIT.
 --><script>    
	var locale_en_advancedsearch_text = "advanced search";
	
	var locale_en_casnumber_cmr_title = "CMR";
	
	var locale_en_casnumber_label_title = "CAS";
	
	var locale_en_cenumber_label_title = "CE";
	
	var locale_en_classofcompound_label_title = "class of compounds";
	
	var locale_en_clearsearch_text = "clear search form";
	
	var locale_en_close = "close";
	
	var locale_en_created = "created";
	
	var locale_en_createperson_mailsubject = "Chimithèque new account\r\n";
	
	var locale_en_delete = "delete";
	
	var locale_en_edit = "edit";
	
	var locale_en_email_placeholder = "enter your email";
	
	var locale_en_empiricalformula_label_title = "empirical formula";
	
	var locale_en_export_text = "export";
	
	var locale_en_hazardstatement_label_title = "hazard statement(s)";
	
	var locale_en_hidedeleted_text = "hide deleted";
	
	var locale_en_linearformula_label_title = "liner formula";
	
	var locale_en_logo_information1 = "Chimithèque logo designed by ";
	
	var locale_en_logo_information2 = "Do not use or copy without her permission.";
	
	var locale_en_menu_bookmark = "my bookmarks";
	
	var locale_en_menu_create_productcard = "create product card";
	
	var locale_en_menu_entity = "entities";
	
	var locale_en_menu_home = "home";
	
	var locale_en_menu_logout = "logout";
	
	var locale_en_menu_password = "change my password";
	
	var locale_en_menu_people = "people";
	
	var locale_en_menu_storelocation = "store locations";
	
	var locale_en_modified = "modified";
	
	var locale_en_password_placeholder = "enter your password";
	
	var locale_en_physicalstate_label_title = "physical state";
	
	var locale_en_precautionarystatement_label_title = "precautionary statement(s)";
	
	var locale_en_product_disposalcomment_title = "disposal comment";
	
	var locale_en_product_msds_title = "MSDS";
	
	var locale_en_product_radioactive_title = "radioactive";
	
	var locale_en_product_remark_title = "remark";
	
	var locale_en_product_restricted_title = "restricted access";
	
	var locale_en_product_threedformula_title = "3D formula";
	
	var locale_en_resetpassword2_text = "reset my password, I am not a robot";
	
	var locale_en_resetpassword_areyourobot = "are you a robot?";
	
	var locale_en_resetpassword_done = "A new temporary password has been sent to %s";
	
	var locale_en_resetpassword_mailsubject1 = "Chimithèque new temporary password\r\n";
	
	var locale_en_resetpassword_mailsubject2 = "Chimithèque password reset link\r\n";
	
	var locale_en_resetpassword_message_mailsentto = "a reinitialization link has been sent to";
	
	var locale_en_resetpassword_text = "reset password";
	
	var locale_en_resetpassword_warning_enteremail = "enter your email in the login form";
	
	var locale_en_s_casnumber = "CAS";
	
	var locale_en_s_casnumber_cmr = "CMR";
	
	var locale_en_s_custom_name_part_of = "part of name";
	
	var locale_en_s_empiricalformula = "emp. formula";
	
	var locale_en_s_hazardstatements = "hazard statement(s)";
	
	var locale_en_s_name = "name";
	
	var locale_en_s_precautionarystatements = "precautionary statement(s)";
	
	var locale_en_s_signalword = "signal word";
	
	var locale_en_s_storage_barecode = "barecode";
	
	var locale_en_s_symbols = "symbol(s)";
	
	var locale_en_save = "save";
	
	var locale_en_search_text = "search";
	
	var locale_en_showdeleted_text = "show deleted";
	
	var locale_en_signalword_label_title = "signal word";
	
	var locale_en_stock_storelocation_sub_title = "including children store locations";
	
	var locale_en_stock_storelocation_title = "in this store location";
	
	var locale_en_storage_barecode_title = "barecode";
	
	var locale_en_storage_batchnumber_title = "batch number";
	
	var locale_en_storage_borrow = "borrow";
	
	var locale_en_storage_clone = "clone";
	
	var locale_en_storage_comment_title = "comment";
	
	var locale_en_storage_entrydate_title = "entry date";
	
	var locale_en_storage_exitdate_title = "exit date";
	
	var locale_en_storage_expirationdate_title = "expiration date";
	
	var locale_en_storage_openingdate_title = "opening date";
	
	var locale_en_storage_quantity_title = "quantity";
	
	var locale_en_storage_restore = "restore";
	
	var locale_en_storage_showhistory = "show history";
	
	var locale_en_storage_unborrow = "unborrow";
	
	var locale_en_submitlogin_text = "enter";
	
	var locale_en_supplier_label_title = "supplier";
	
	var locale_en_switchproductview_text = "switch to product view";
	
	var locale_en_switchstorageview_text = "switch to storage view";
	
	var locale_en_test = "One test";
	
    
	var locale_fr_advancedsearch_text = "recherche avancée";
	
	var locale_fr_casnumber_cmr_title = "CMR";
	
	var locale_fr_casnumber_label_title = "CAS";
	
	var locale_fr_cenumber_label_title = "CE";
	
	var locale_fr_classofcompound_label_title = "famille chimique";
	
	var locale_fr_clearsearch_text = "effacer le formulaire";
	
	var locale_fr_close = "fermer";
	
	var locale_fr_created = "créé";
	
	var locale_fr_createperson_mailsubject = "Chimithèque nouveau compte\r\n";
	
	var locale_fr_delete = "supprimer";
	
	var locale_fr_edit = "editer";
	
	var locale_fr_email_placeholder = "entrez votre email";
	
	var locale_fr_empiricalformula_label_title = "formule brute";
	
	var locale_fr_export_text = "exporter";
	
	var locale_fr_hazardstatement_label_title = "mention(s) de danger H-EUH";
	
	var locale_fr_hidedeleted_text = "cacher supprimés";
	
	var locale_fr_linearformula_label_title = "formule linéaire";
	
	var locale_fr_logo_information1 = "Logo Chimithèque réalisé par ";
	
	var locale_fr_logo_information2 = "Ne pas utiliser ou copier sans sa permission.";
	
	var locale_fr_menu_bookmark = "mes favoris";
	
	var locale_fr_menu_create_productcard = "créer fiche produit";
	
	var locale_fr_menu_entity = "entités";
	
	var locale_fr_menu_home = "accueil";
	
	var locale_fr_menu_logout = "déconnexion";
	
	var locale_fr_menu_password = "changer mon mot de passe";
	
	var locale_fr_menu_people = "utilisateurs";
	
	var locale_fr_menu_storelocation = "entrepôts";
	
	var locale_fr_modified = "modifié";
	
	var locale_fr_password_placeholder = "entrez votre mot de passe";
	
	var locale_fr_physicalstate_label_title = "état physique";
	
	var locale_fr_precautionarystatement_label_title = "conseil(s) de prudence P";
	
	var locale_fr_product_disposalcomment_title = "commentaire de destruction";
	
	var locale_fr_product_msds_title = "FDS";
	
	var locale_fr_product_radioactive_title = "radioactif";
	
	var locale_fr_product_remark_title = "remarque";
	
	var locale_fr_product_restricted_title = "accès restreint";
	
	var locale_fr_product_threedformula_title = "formule 3D";
	
	var locale_fr_resetpassword2_text = "réinitialiser mon mot de passe, je ne suis pas un robot";
	
	var locale_fr_resetpassword_areyourobot = "êtes vous un robot ?";
	
	var locale_fr_resetpassword_done = "Un nouveau mot de passe temporaire a été envoyé à %s";
	
	var locale_fr_resetpassword_mailsubject1 = "Chimithèque nouveau mot de passe temporaire\r\n";
	
	var locale_fr_resetpassword_mailsubject2 = "Chimithèque lien de réinitialisation de mot de passe\r\n";
	
	var locale_fr_resetpassword_message_mailsentto = "un mail de réinitialisation a été envoyé à";
	
	var locale_fr_resetpassword_text = "réinitialiser mon mot de passe";
	
	var locale_fr_resetpassword_warning_enteremail = "entrez votre adresse mail dans le formulaire";
	
	var locale_fr_s_casnumber = "CAS";
	
	var locale_fr_s_custom_name_part_of = "partie du nom";
	
	var locale_fr_s_empiricalformula = "formule brute";
	
	var locale_fr_s_hazardstatements = "mention(s) de danger H-EUH";
	
	var locale_fr_s_name = "nom";
	
	var locale_fr_s_precautionarystatements = "conseil(s) de prudence P";
	
	var locale_fr_s_signalword = "mention d'avertissement";
	
	var locale_fr_s_storage_barecode = "code barre";
	
	var locale_fr_s_symbols = "symbole(s)";
	
	var locale_fr_save = "enregistrer";
	
	var locale_fr_search_text = "rechercher";
	
	var locale_fr_showdeleted_text = "voir supprimés";
	
	var locale_fr_signalword_label_title = "mention d'avertissement";
	
	var locale_fr_storage_barecode_title = "code barre";
	
	var locale_fr_storage_batchnumber_title = "numéro de lot";
	
	var locale_fr_storage_borrow = "emprunter";
	
	var locale_fr_storage_clone = "cloner";
	
	var locale_fr_storage_comment_title = "commentaire";
	
	var locale_fr_storage_entrydate_title = "date d'entrée";
	
	var locale_fr_storage_exitdate_title = "date de sortie";
	
	var locale_fr_storage_expirationdate_title = "date d'expiration";
	
	var locale_fr_storage_openingdate_title = "date d'ouverture";
	
	var locale_fr_storage_quantity_title = "quantité";
	
	var locale_fr_storage_restore = "restaurer";
	
	var locale_fr_storage_showhistory = "voir historique";
	
	var locale_fr_storage_unborrow = "restituer";
	
	var locale_fr_submitlogin_text = "entrer";
	
	var locale_fr_supplier_label_title = "fournisseur";
	
	var locale_fr_switchproductview_text = "vue par produits";
	
	var locale_fr_switchstorageview_text = "vue par stockages";
	
	var locale_fr_test = "Un test";
	

</script>`
)

func Entitycreate(c ViewContainer, wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(index__0)
	WriteAll(c.ProxyPath+"css/bootstrap.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-table.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/select2.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-colorpicker.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/fontawesome.all.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/chimitheque.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/materialdesignicons.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-toggle.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/animate.min.css", true, buffer)
	buffer.WriteString(index__9)
	WriteAll(c.ProxyPath+"js/jquery-3.3.1.min.js", true, buffer)
	buffer.WriteString(index__10)
	WriteAll(c.ProxyPath+"img/logo_chimitheque_small.png", true, buffer)
	buffer.WriteString(index__11)

	if HasPermission(c.PersonID, "r", "products", -2) {
		buffer.WriteString(index__35)
		WriteAll(c.ProxyPath+"v/products", true, buffer)
		buffer.WriteString(index__36)
		WriteAll(T("menu_home", 1), true, buffer)
		buffer.WriteString(index__37)

	}
	if HasPermission(c.PersonID, "r", "products", -2) {
		buffer.WriteString(index__35)
		WriteAll(c.ProxyPath+"v/products?bookmark=true", true, buffer)
		buffer.WriteString(index__39)
		WriteAll(T("menu_bookmark", 1), true, buffer)
		buffer.WriteString(index__37)

	}
	if HasPermission(c.PersonID, "w", "products", -2) {
		buffer.WriteString(index__41)
		WriteAll(c.ProxyPath+"vc/products", true, buffer)
		buffer.WriteString(index__42)
		WriteAll(T("menu_create_productcard", 1), true, buffer)
		buffer.WriteString(index__37)

	}
	if HasPermission(c.PersonID, "r", "entities", -2) {
		buffer.WriteString(index__44)
		WriteAll(T("menu_entity", 1), true, buffer)
		buffer.WriteString(index__45)
		WriteAll(c.ProxyPath+"v/entities", true, buffer)
		buffer.WriteString(index__46)

		if HasPermission(c.PersonID, "all", "all", -1) {
			buffer.WriteString(index__48)
			WriteAll(c.ProxyPath+"vc/entities", true, buffer)
			buffer.WriteString(index__49)

		}
		buffer.WriteString(index__47)

	}
	if HasPermission(c.PersonID, "r", "storages", -2) {
		buffer.WriteString(index__50)
		WriteAll(T("menu_storelocation", 1), true, buffer)
		buffer.WriteString(index__45)
		WriteAll(c.ProxyPath+"v/storelocations", true, buffer)
		buffer.WriteString(index__46)

		if HasPermission(c.PersonID, "all", "all", -2) {
			buffer.WriteString(index__48)
			WriteAll(c.ProxyPath+"vc/storelocations", true, buffer)
			buffer.WriteString(index__49)

		}
		buffer.WriteString(index__47)

	}
	if HasPermission(c.PersonID, "r", "people", -2) {
		buffer.WriteString(index__56)
		WriteAll(T("menu_people", 1), true, buffer)
		buffer.WriteString(index__45)
		WriteAll(c.ProxyPath+"v/people", true, buffer)
		buffer.WriteString(index__46)

		if HasPermission(c.PersonID, "w", "people", -2) {
			buffer.WriteString(index__48)
			WriteAll(c.ProxyPath+"vc/people", true, buffer)
			buffer.WriteString(index__49)

		}
		buffer.WriteString(index__47)

	}
	buffer.WriteString(index__12)
	WriteAll(c.ProxyPath+"vu/peoplepass", true, buffer)
	buffer.WriteString(index__13)
	WriteAll(T("menu_password", 1), true, buffer)
	buffer.WriteString(index__14)
	WriteAll(c.ProxyPath+"delete-token", true, buffer)
	buffer.WriteString(index__15)
	WriteAll(T("menu_logout", 1), true, buffer)
	buffer.WriteString(create__16)

	{
		var (
			iconitem   = "creation"
			iconaction = "store"
			label      = "create entity"
		)

		buffer.WriteString(index_2__68)
		WriteEscString("mdi-"+iconitem+" mdi mdi-48px", buffer)
		buffer.WriteString(index_2__69)
		WriteEscString("mdi-"+iconaction+" mdi mdi-18px", buffer)
		buffer.WriteString(index_2__70)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__71)

	}

	buffer.WriteString(create__17)

	{
		var (
			label = "name"
			name  = "entity_name"
		)

		buffer.WriteString(index_2__72)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__73)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__74)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__75)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__77)
	}

	buffer.WriteString(index_2__18)

	{
		var (
			label = "description"
			name  = "entity_description"
		)

		buffer.WriteString(index_2__72)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__73)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__74)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__75)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__77)
	}

	buffer.WriteString(index_2__18)

	{
		var (
			label = "manager(s)"
			name  = "managers"
		)

		buffer.WriteString(index_2__72)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__73)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__86)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__75)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__88)

	}

	buffer.WriteString(index_2__20)
	WriteAll(T("save", 1), true, buffer)
	buffer.WriteString(create__21)

	json, _ := json.Marshal(c)

	var out string
	for key, value := range c.URLValues {
		out += fmt.Sprintf("URLValues.set(%s, %s)\n", key, value)
	}

	buffer.WriteString(index__17)
	WriteAll(c.ProxyPath, false, buffer)
	buffer.WriteString(index__18)
	buffer.WriteString(fmt.Sprintf("%s", json))
	buffer.WriteString(index__19)
	buffer.WriteString(out)
	buffer.WriteString(index__20)
	WriteAll(c.ProxyPath+"js/jquery.formautofill.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/jquery.validate.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/jquery.validate.additional-methods.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/select2.full.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/popper.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap-table.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap-confirmation.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap-colorpicker.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/bootstrap-toggle.min.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/JSmol.lite.nojq.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/chim/gjs-common.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/chim/chimcommon.js", true, buffer)
	buffer.WriteString(index__21)
	WriteAll(c.ProxyPath+"js/chim/login.js", true, buffer)
	buffer.WriteString(index_2__40)

}
