// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"encoding/json"
	"fmt"
	"io"
)

const (
	index_6__30  = `</span></a></li></ul></div></nav><div id="search" class="row pt-sm-4 pb-sm-4 pl-sm-2 pr-sm-2 mt-sm-2 mb-sm-2 ml-sm-5 mr-sm-5 bg-light border rounded collapse show">`
	index_6__45  = `</span></button></div></div></div></div><div class="row"><div class="col-sm-8"><div id="filter-item"></div></div><div class="col-sm-2 d-flex justify-content-end"><div id="button-store"></div></div><div class="col-sm-2 d-flex justify-content-end"><div id="button-stock"></div></div></div><div id="toolbar" class="row"><div class="col toggleable"><button class="btn btn-link" id="switchview" type="button" onclick="switchProductStorageView()"><span class="mdi mdi-tag mdi-24px iconlabel">`
	index_6__47  = `</span></button></div><div class="col"><button id="s_storage_archive_button" class="btn btn-link" type="button" data-toggle="button" aria-pressed="true" autocomplete="off"><span class="mdi mdi-delete mdi-24px iconlabel">`
	index_6__48  = `</span></button></div></div><div id="stock" class="modal fade" role="dialog" tabindex="-1" aria-labelledby="stockLabel" aria-hidden="true"><div class="modal-dialog modal-lg" role="document"><div class="modal-content"><div class="modal-body" id="stock-body"><span class="mdi mdi-36px mdi-spin mdi-autorenew"></span></div><div class="modal-footer"><button class="btn btn-link" type="button" data-dismiss="modal"><span class="mdi mdi-close-box mdi-24px iconlabel">`
	index_6__49  = `</span></button></div></div></div></div><div id="exportlink" class="modal fade" role="dialog" tabindex="-1" aria-labelledby="exportlinkLabel" aria-hidden="true"><div class="modal-dialog modal-sm" role="document"><div class="modal-content"><div class="modal-body mx-auto" id="exportlink-body"></div><div class="modal-footer"><button class="btn btn-link" type="button" data-dismiss="modal"><span class="mdi mdi-close-box mdi-24px iconlabel">`
	index_6__50  = `</span></button></div></div></div></div><div id="borrow" class="modal fade" role="dialog" tabindex="-1" aria-labelledby="borrowLabel" aria-hidden="true"><div class="modal-dialog modal-lg" role="document"><div class="modal-content"><div class="modal-body" id="borrow-body"><form id="borrowing"><input id="bstorage_id" type="hidden" name="bstorage_id" value=""/><div class="form-group row"><div class="form-group col-sm-auto"><span class="badge badge-pill badge-danger">&nbsp;</span></div><div class="form-group col-sm-11">`
	index_6__51  = `</div></div><div class="form-group row"><div class="col-sm-12">`
	index_6__52  = `</div></div></form></div><div class="modal-footer"><button class="btn btn-link" type="button" onclick="saveBorrowing()"><span class="mdi mdi-content-save mdi-24px iconlabel">`
	index_6__53  = `</span></button><button class="btn btn-link" type="button" data-dismiss="modal"><span class="mdi mdi-close-box mdi-24px iconlabel">`
	index_6__54  = `</span></button></div></div></div></div><div id="accordion"><div id="list-collapse" class="collapse show" data-parent="#accordion"><header class="row"><div class="col-sm-12"><table id="table" data-toggle="table" data-striped="true" data-search="false" data-toolbar="#toolbar" data-side-pagination="server" data-page-list="[5, 10, 20, 50, 100, 200, 500]" data-pagination="true" data-ajax="getData" data-query-params="queryParams" data-sort-name="name.name_label" data-detail-view="true" data-detail-formatter="detailFormatter" data-row-attributes="rowAttributes"><thead><tr><!-- th(data-field='storage_id' data-formatter='storage_idFormatter' data-sortable='true') ID --><!-- th(data-field='storage_modificationdate' data-formatter='dateFormatter' data-sortable='true') modification date --><th data-field="storage_quantity" data-formatter="storage_quantityFormatter">quantity</th><th data-field="storage_barecode" data-formatter="storage_barecodeFormatter" data-sortable="true">barecode</th><th class="th-width-200" data-field="product.name.name_label" data-formatter="storage_productFormatter" data-sortable="true">product</th><th data-field="storelocation.storelocation_fullpath" data-sortable="true" data-formatter="storelocation_fullpathFormatter">store location</th><th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents"></th></tr></thead></table></div></header></div><div id="edit-collapse" class="collapse" data-parent="#accordion">`
	index_6__55  = `<div class="row"><div class="d-flex justify-content-center"><div id="filter-product"></div></div></div><form id="storage"><input id="index" type="hidden" name="index" value=""/><input id="storage_id" type="hidden" name="storage_id" value=""/><input id="exactMatchSupplier" type="hidden"/><div class="form-group row"><div class="form-group col-sm-auto"><span class="badge badge-pill badge-danger">&nbsp;</span></div><div class="form-group col-sm-11">`
	index_6__56  = `</div></div><div class="form-group row"><div class="col-sm-6">`
	index_6__59  = `</div></div><div class="form-group row"><div class="col-sm-3">`
	index_6__60  = `</div><div class="col-sm-3">`
	index_6__68  = `</div></div></form><button id="save" class="btn btn-link" type="button" onclick="saveStorage()"><span class="mdi mdi-content-save mdi-24px iconlabel">`
	index_6__88  = `"></script><script src="../js/chim/product_storage.js"></script><script src="../js/chim/storage.js"></script></body></html>`
	index_6__190 = `</label><input class="form-control" type="number" id="`
	index_6__193 = `" step="`
	index_6__194 = `" min="`
	index_6__195 = `" max="`
	index_6__210 = `</label><input class="form-control" type="date" id="`
)

func Storageindex(c ViewContainer, wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(index__0)
	WriteAll(c.ProxyPath+"css/bootstrap.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-table.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/select2.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-colorpicker.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/fontawesome.all.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/chimitheque.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/materialdesignicons.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/bootstrap-toggle.min.css", true, buffer)
	buffer.WriteString(index__1)
	WriteAll(c.ProxyPath+"css/animate.min.css", true, buffer)
	buffer.WriteString(index__9)
	WriteAll(c.ProxyPath+"js/jquery-3.3.1.min.js", true, buffer)
	buffer.WriteString(index__10)
	WriteAll(c.ProxyPath+"img/logo_chimitheque_small.png", true, buffer)
	buffer.WriteString(index__11)
	WriteAll(c.ProxyPath+"v/products", true, buffer)
	buffer.WriteString(index__12)
	WriteAll(T("menu_home", 1), true, buffer)
	buffer.WriteString(index__13)
	WriteAll(c.ProxyPath+"v/products?bookmark=true", true, buffer)
	buffer.WriteString(index__14)
	WriteAll(T("menu_bookmark", 1), true, buffer)
	buffer.WriteString(index__15)
	WriteAll(c.ProxyPath+"vc/products", true, buffer)
	buffer.WriteString(index__16)
	WriteAll(T("menu_create_productcard", 1), true, buffer)
	buffer.WriteString(index__17)
	WriteAll(T("menu_entity", 1), true, buffer)
	buffer.WriteString(index__18)
	WriteAll(c.ProxyPath+"v/entities", true, buffer)
	buffer.WriteString(index__19)
	WriteAll(c.ProxyPath+"vc/entities", true, buffer)
	buffer.WriteString(index__20)
	WriteAll(T("menu_storelocation", 1), true, buffer)
	buffer.WriteString(index__18)
	WriteAll(c.ProxyPath+"v/storelocations", true, buffer)
	buffer.WriteString(index__22)
	WriteAll(c.ProxyPath+"vc/storelocations", true, buffer)
	buffer.WriteString(index__23)
	WriteAll(T("menu_people", 1), true, buffer)
	buffer.WriteString(index__18)
	WriteAll(c.ProxyPath+"v/people", true, buffer)
	buffer.WriteString(index__25)
	WriteAll(c.ProxyPath+"vc/people", true, buffer)
	buffer.WriteString(index__26)
	WriteAll(c.ProxyPath+"vu/peoplepass", true, buffer)
	buffer.WriteString(index__27)
	WriteAll(T("menu_password", 1), true, buffer)
	buffer.WriteString(index__28)
	WriteAll(c.ProxyPath+"delete-token", true, buffer)
	buffer.WriteString(index__29)
	WriteAll(T("menu_logout", 1), true, buffer)
	buffer.WriteString(index_6__30)

	{
		var (
			name  = "s_entity"
			value = ""
		)

		buffer.WriteString(index_4__90)
		WriteEscString("hidden_"+name, buffer)
		buffer.WriteString(index_4__91)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__92)
		WriteEscString(value, buffer)
		buffer.WriteString(index_4__93)
	}

	{
		var (
			name  = "s_product"
			value = ""
		)

		buffer.WriteString(index_4__90)
		WriteEscString("hidden_"+name, buffer)
		buffer.WriteString(index_4__91)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__92)
		WriteEscString(value, buffer)
		buffer.WriteString(index_4__93)
	}

	{
		var (
			name  = "s_history"
			value = ""
		)

		buffer.WriteString(index_4__90)
		WriteEscString("hidden_"+name, buffer)
		buffer.WriteString(index_4__91)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__92)
		WriteEscString(value, buffer)
		buffer.WriteString(index_4__93)
	}

	{
		var (
			name  = "s_storage"
			value = ""
		)

		buffer.WriteString(index_4__90)
		WriteEscString("hidden_"+name, buffer)
		buffer.WriteString(index_4__91)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__92)
		WriteEscString(value, buffer)
		buffer.WriteString(index_4__93)
	}

	{
		var (
			name  = "s_storage_archive"
			value = ""
		)

		buffer.WriteString(index_4__90)
		WriteEscString("hidden_"+name, buffer)
		buffer.WriteString(index_4__91)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__92)
		WriteEscString(value, buffer)
		buffer.WriteString(index_4__93)
	}

	{
		var (
			name  = "s_bookmark"
			value = ""
		)

		buffer.WriteString(index_4__90)
		WriteEscString("hidden_"+name, buffer)
		buffer.WriteString(index_4__91)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__92)
		WriteEscString(value, buffer)
		buffer.WriteString(index_4__93)
	}

	buffer.WriteString(index_4__31)

	{
		var (
			name = "s_storelocation"
			icon = "docker"
		)

		buffer.WriteString(index_4__114)
		WriteEscString("mdi-"+icon+" mdi mdi-36px", buffer)
		buffer.WriteString(index_4__115)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__117)

	}

	buffer.WriteString(index_4__32)

	{
		var (
			label = T("s_custom_name_part_of", 1)
			name  = "s_custom_name_part_of"
		)

		buffer.WriteString(index_4__118)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_4__120)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__123)

	}

	buffer.WriteString(index_4__33)

	{
		var (
			label = T("s_name", 1)
			name  = "s_name"
		)

		buffer.WriteString(index_4__118)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_4__126)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__117)

	}

	buffer.WriteString(index_4__34)

	{
		var (
			label = T("s_casnumber", 1)
			name  = "s_casnumber"
		)

		buffer.WriteString(index_4__118)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_4__126)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__117)

	}

	buffer.WriteString(index_4__34)

	{
		var (
			label = T("s_empiricalformula", 1)
			name  = "s_empiricalformula"
		)

		buffer.WriteString(index_4__118)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_4__126)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__117)

	}

	buffer.WriteString(index_4__34)

	{
		var (
			label = T("s_storage_barecode", 1)
			name  = "s_storage_barecode"
		)

		buffer.WriteString(index_4__118)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_4__120)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__123)

	}

	buffer.WriteString(index_4__37)

	{
		var (
			label = T("s_signalword", 1)
			name  = "s_signalword"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__149)

	}

	buffer.WriteString(index_4__38)

	{
		var (
			label = T("s_symbols", 1)
			name  = "s_symbols"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__78)

	}

	buffer.WriteString(index_4__39)

	{
		var (
			label = T("s_hazardstatements", 1)
			name  = "s_hazardstatements"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__78)

	}

	buffer.WriteString(index_4__38)

	{
		var (
			label = T("s_precautionarystatements", 1)
			name  = "s_precautionarystatements"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__78)

	}

	buffer.WriteString(index_4__39)

	{
		var (
			label = T("s_casnumber_cmr", 1)
			name  = "s_casnumber_cmr"
		)

		buffer.WriteString(index_4__165)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__166)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteAll(label, true, buffer)
		buffer.WriteString(index_4__168)
	}

	buffer.WriteString(index_4__42)
	WriteAll(T("clearsearch_text", 1), true, buffer)
	buffer.WriteString(index_4__43)
	WriteAll(T("search_text", 1), true, buffer)
	buffer.WriteString(index_4__44)
	WriteAll(T("advancedsearch_text", 1), true, buffer)
	buffer.WriteString(index_6__45)
	WriteAll(T("switchproductview_text", 1), true, buffer)
	buffer.WriteString(index_4__46)
	WriteAll(T("export_text", 1), true, buffer)
	buffer.WriteString(index_6__47)
	WriteAll(T("showdeleted_text", 1), true, buffer)
	buffer.WriteString(index_6__48)
	WriteAll(T("close", 1), true, buffer)
	buffer.WriteString(index_6__49)
	WriteAll(T("close", 1), true, buffer)
	buffer.WriteString(index_6__50)

	{
		var (
			label = "borrower"
			name  = "borrower"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__149)

	}

	buffer.WriteString(index_6__51)

	{
		var (
			label = "comment"
			name  = "borrowing_comment"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_4__271)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__274)

	}

	buffer.WriteString(index_6__52)
	WriteAll(T("save", 1), true, buffer)
	buffer.WriteString(index_6__53)
	WriteAll(T("close", 1), true, buffer)
	buffer.WriteString(index_6__54)

	{
		var (
			iconitem   = "border-color"
			iconaction = "forklift"
			label      = "update storage"
		)

		buffer.WriteString(index_2__58)
		WriteEscString("mdi-"+iconitem+" mdi mdi-48px", buffer)
		buffer.WriteString(index_2__59)
		WriteEscString("mdi-"+iconaction+" mdi mdi-18px", buffer)
		buffer.WriteString(index_2__60)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__61)

	}

	buffer.WriteString(index_6__55)

	{
		var (
			label = "store location"
			name  = "storelocation"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__149)

	}

	buffer.WriteString(index_6__56)

	{
		var (
			label = "quantity"
			name  = "storage_quantity"
			step  = "any"
			min   = "1"
			max   = "10000000"
			value = ""
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_6__190)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_6__193)
		WriteEscString(step, buffer)
		buffer.WriteString(index_6__194)
		WriteEscString(min, buffer)
		buffer.WriteString(index_6__195)
		WriteEscString(max, buffer)
		buffer.WriteString(index_4__92)
		WriteEscString(value, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_4__34)

	{
		var (
			label = "unit"
			name  = "unit"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__149)

	}

	buffer.WriteString(index_6__51)

	{
		var (
			label = "supplier"
			name  = "supplier"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__76)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__149)

	}

	buffer.WriteString(index_6__59)

	{
		var (
			label = "entry date"
			name  = "storage_entrydate"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_6__210)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_6__60)

	{
		var (
			label = "exit date"
			name  = "storage_exitdate"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_6__210)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_6__60)

	{
		var (
			label = "opening date"
			name  = "storage_openingdate"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_6__210)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_6__60)

	{
		var (
			label = "expiration date"
			name  = "storage_expirationdate"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_6__210)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_6__56)

	{
		var (
			label = "reference"
			name  = "storage_reference"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__64)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_4__34)

	{
		var (
			label = "batch number"
			name  = "storage_batchnumber"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__64)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_6__51)

	{
		var (
			label = "barecode"
			name  = "storage_barecode"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__64)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_6__51)

	{
		var (
			label = "comment"
			name  = "storage_comment"
		)

		buffer.WriteString(index_2__62)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_2__64)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__65)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__66)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__67)
	}

	buffer.WriteString(index_6__51)

	{
		var (
			label = "to destroy"
			name  = "storage_todestroy"
		)

		buffer.WriteString(index_4__165)
		WriteEscString(name, buffer)
		buffer.WriteString(index_4__166)
		WriteEscString(name, buffer)
		buffer.WriteString(index_2__63)
		WriteEscString(label, buffer)
		buffer.WriteString(index_4__168)
	}

	buffer.WriteString(index_6__68)
	WriteAll(T("save", 1), true, buffer)
	buffer.WriteString(index_4__70)
	WriteAll(T("close", 1), true, buffer)
	buffer.WriteString(index_2__39)

	json, _ := json.Marshal(c)

	var out string
	for key, value := range c.URLValues {
		out += fmt.Sprintf("URLValues.set(%s, %s)\n", key, value)
	}

	buffer.WriteString(index__31)
	WriteAll(c.ProxyPath, false, buffer)
	buffer.WriteString(index__32)
	buffer.WriteString(fmt.Sprintf("%s", json))
	buffer.WriteString(index__33)
	buffer.WriteString(out)
	buffer.WriteString(index__34)
	WriteAll(c.ProxyPath+"js/jquery.formautofill.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/jquery.validate.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/jquery.validate.additional-methods.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/select2.full.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/popper.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/bootstrap.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/bootstrap-table.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/bootstrap-confirmation.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/bootstrap-colorpicker.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/bootstrap-toggle.min.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/JSmol.lite.nojq.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/chim/gjs-common.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/chim/chimcommon.js", true, buffer)
	buffer.WriteString(index__35)
	WriteAll(c.ProxyPath+"js/chim/login.js", true, buffer)
	buffer.WriteString(index_6__88)

}
