PRAGMA foreign_keys = false;
INSERT INTO "name" VALUES (1,'name_1');
INSERT INTO "name" VALUES (2,'name_2');
INSERT INTO "name" VALUES (3,'name_3');
INSERT INTO "name" VALUES (4,'name_4');
INSERT INTO "name" VALUES (5,'name_5');
INSERT INTO "product" ('product_id','product_type','person','name') VALUES (1,'chem',1,1);
INSERT INTO "product" ('product_id','product_type','person','name') VALUES (2,'chem',1,2);
INSERT INTO "product" ('product_id','product_type','person','name') VALUES (3,'chem',1,3);
INSERT INTO "product" ('product_id','product_type','person','name') VALUES (4,'chem',1,4);
INSERT INTO "product" ('product_id','product_type','person','name') VALUES (5,'chem',1,5);
INSERT INTO "entity" VALUES (1,'entity_1','entity_1');
INSERT INTO "entity" VALUES (2,'entity_2','entity_2');
INSERT INTO "entity" VALUES (3,'entity_3','entity_3');
INSERT INTO "entitypeople" VALUES (1,2);
INSERT INTO "entitypeople" VALUES (2,3);
INSERT INTO "store_location" VALUES (1,'location_1a','#FFFFFF',true,'',1,NULL);
INSERT INTO "store_location" VALUES (2,'location_1b','#FFFFFF',true,'',1,NULL);
INSERT INTO "store_location" VALUES (3,'location_2a','#FFFFFF',true,'',2,NULL);
INSERT INTO "store_location" VALUES (4,'location_2b','#FFFFFF',false,'',2,NULL);
INSERT INTO "store_location" VALUES (5,'location_2bb','#FFFFFF',true,'',2,4);
INSERT INTO "storage" ('storage_id','storage_creation_date','storage_modification_date','person','product','store_location') VALUES (1,1326886027,1326886027,1,1,1);
INSERT INTO "storage" ('storage_id','storage_creation_date','storage_modification_date','person','product','store_location') VALUES (2,1326886027,1326886027,1,2,2);
INSERT INTO "storage" ('storage_id','storage_creation_date','storage_modification_date','person','product','store_location') VALUES (3,1326886027,1326886027,1,3,3);
INSERT INTO "storage" ('storage_id','storage_creation_date','storage_modification_date','person','product','store_location') VALUES (4,1326886027,1326886027,1,4,4);
INSERT INTO "person" VALUES (2,'manager1@chimitheque.fr');
INSERT INTO "person" VALUES (3,'manager2@chimitheque.fr');
INSERT INTO "person" VALUES (4,'user1@chimitheque.fr');
INSERT INTO "person" VALUES (5,'user2@chimitheque.fr');
INSERT INTO "personentities" VALUES (2,1);
INSERT INTO "personentities" VALUES (3,2);
INSERT INTO "personentities" VALUES (4,1);
INSERT INTO "personentities" VALUES (5,2);
INSERT INTO "permission" VALUES (2,2,'r','products',-1);
INSERT INTO "permission" VALUES (3,2,'all','all',1);
INSERT INTO "permission" VALUES (4,2,'w','products',-1);
INSERT INTO "permission" VALUES (5,2,'w','rproducts',-1);
INSERT INTO "permission" VALUES (6,3,'all','all',2);
INSERT INTO "permission" VALUES (7,3,'w','products',-1);
INSERT INTO "permission" VALUES (8,3,'w','rproducts',-1);
INSERT INTO "permission" VALUES (9,4,'r','entities',1);
INSERT INTO "permission" VALUES (10,4,'w','products',-1);
INSERT INTO "permission" VALUES (11,4,'r','rproducts',-1);
INSERT INTO "permission" VALUES (12,4,'w','storages',1);
INSERT INTO "permission" VALUES (13,5,'r','entities',2);
INSERT INTO "permission" VALUES (14,5,'w','products',-1);
INSERT INTO "permission" VALUES (15,5,'r','rproducts',-1);
INSERT INTO "permission" VALUES (16,5,'w','storages',2);
INSERT INTO "hazard_statement" (hazard_statement_label, hazard_statement_reference) VALUES ('hazard_statement1','hazard_statement1-ref');
INSERT INTO "hazard_statement" (hazard_statement_label, hazard_statement_reference) VALUES ('aa hazard_statement1','aa hazard_statement1-ref');
INSERT INTO "hazard_statement" (hazard_statement_label, hazard_statement_reference) VALUES ('hazard_statement2','hazard_statement2-ref');
INSERT INTO "hazard_statement" (hazard_statement_label, hazard_statement_reference) VALUES ('hazard_statement3','hazard_statement3-ref');
INSERT INTO "precautionary_statement" (precautionary_statement_label, precautionary_statement_reference) VALUES ('precautionary_statement1', 'precautionary_statement1-ref');
INSERT INTO "precautionary_statement" (precautionary_statement_label, precautionary_statement_reference) VALUES ('aa precautionary_statement1', 'aa precautionary_statement1-ref');
INSERT INTO "precautionary_statement" (precautionary_statement_label, precautionary_statement_reference) VALUES ('precautionary_statement2', 'precautionary_statement2-ref');
INSERT INTO "precautionary_statement" (precautionary_statement_label, precautionary_statement_reference) VALUES ('precautionary_statement3', 'precautionary_statement3-ref');
INSERT INTO "producer" (producer_label) VALUES ('FAKE_PRODUCER');
INSERT INTO "producer" (producer_label) VALUES ('FAKE_PRODUCER ONE');
INSERT INTO "producer" (producer_label) VALUES ('FAKE_PRODUCER TWO');
INSERT INTO "producer" (producer_label) VALUES ('FAKE_PRODUCER THREE');
INSERT INTO "producer" (producer_label) VALUES ('AAA FAKE_PRODUCER');
INSERT INTO "producer" (producer_label) VALUES ('YET ANOTHER PRODUCER');
INSERT INTO "producer" (producer_label) VALUES ('12345');
INSERT INTO "producer" (producer_id, producer_label) VALUES (300, 'FAKE_PRODUCER_1');
INSERT INTO "producer" (producer_id, producer_label) VALUES (301, 'FAKE_PRODUCER_2');
INSERT INTO "producer_ref" (producer_ref_label, producer) VALUES ('1_ref1', 300);
INSERT INTO "producer_ref" (producer_ref_label, producer) VALUES ('1_ref2', 301);
INSERT INTO "producer_ref" (producer_ref_label, producer) VALUES ('1234', 300);
INSERT INTO "producer_ref" (producer_ref_label, producer) VALUES ('12', 300);
INSERT INTO "producer_ref" (producer_ref_label, producer) VALUES ('2_ref1', 301);
INSERT INTO "producer_ref" (producer_ref_label, producer) VALUES ('2_ref2', 301);
INSERT INTO "producer_ref" (producer_ref_label, producer) VALUES ('1234', 301);
INSERT INTO "producer_ref" (producer_ref_label, producer) VALUES ('22', 301);
INSERT INTO "supplier" (supplier_label) VALUES ('FAKE_SUPPLIER');
INSERT INTO "supplier" (supplier_label) VALUES ('FAKE_SUPPLIER ONE');
INSERT INTO "supplier" (supplier_label) VALUES ('FAKE_SUPPLIER TWO');
INSERT INTO "supplier" (supplier_label) VALUES ('FAKE_SUPPLIER THREE');
INSERT INTO "supplier" (supplier_label) VALUES ('AAA FAKE_SUPPLIER');
INSERT INTO "supplier" (supplier_label) VALUES ('YET ANOTHER SUPPLIER');
INSERT INTO "supplier" (supplier_label) VALUES ('12345');
INSERT INTO "supplier" (supplier_id, supplier_label) VALUES (300, 'FAKE_SUPPLIER_1');
INSERT INTO "supplier" (supplier_id, supplier_label) VALUES (301, 'FAKE_SUPPLIER_2');
INSERT INTO "supplier_ref" (supplier_ref_label, supplier) VALUES ('1_ref1', 300);
INSERT INTO "supplier_ref" (supplier_ref_label, supplier) VALUES ('1_ref2', 300);
INSERT INTO "supplier_ref" (supplier_ref_label, supplier) VALUES ('1234', 300);
INSERT INTO "supplier_ref" (supplier_ref_label, supplier) VALUES ('12', 300);
INSERT INTO "supplier_ref" (supplier_ref_label, supplier) VALUES ('2_ref1', 301);
INSERT INTO "supplier_ref" (supplier_ref_label, supplier) VALUES ('2_ref2', 301);
INSERT INTO "supplier_ref" (supplier_ref_label, supplier) VALUES ('1234', 301);
INSERT INTO "supplier_ref" (supplier_ref_label, supplier) VALUES ('22', 301);
PRAGMA foreign_keys = true;
