package main

import (
	"fmt"
	"log"
	"os"
	"text/template"

	"regexp"

	"github.com/tbellembois/gochimitheque/locales"
)

// output file template
var packageTemplate = template.Must(template.New("").Delims("[[", "]]").Parse(`// Code generated by go generate; DO NOT EDIT.
| {{define "LOCALEJS"}}

script.
    [[ range $k, $v := .EN ]]
	var [[ $k ]] = "[[ $v ]]";
	[[ end ]]
    [[ range $k, $v := .FR ]]
	var [[ $k ]] = "[[ $v ]]";
	[[ end ]]

| {{end}}
`))

// locales regexp
var r = regexp.MustCompile("\\[(\\S+)\\]\\n\\s+one = \"(.+)\"")

// locales map
var m_en map[string]string
var m_fr map[string]string

// template date
type Tdata struct {
	EN map[string]string
	FR map[string]string
}

func main() {
	m_en = make(map[string]string)
	m_fr = make(map[string]string)

	// finding matches
	ms_en := r.FindAllStringSubmatch(string(locales.LOCALES_EN), -1)
	for _, v := range ms_en {
		//fmt.Printf("%d. %s\n", k, v)
		//fmt.Printf("%s -> %s\n", v[1], v[2])
		k := fmt.Sprintf("locale_en_%s", v[1])
		m_en[k] = v[2]
	}
	ms_fr := r.FindAllStringSubmatch(string(locales.LOCALES_FR), -1)
	for _, v := range ms_fr {
		//fmt.Printf("%d. %s\n", k, v)
		//fmt.Printf("%s -> %s\n", v[1], v[2])
		k := fmt.Sprintf("locale_fr_%s", v[1])
		m_fr[k] = v[2]
	}

	// opening output file
	f, err := os.Create("static/templates/localejs.jade")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	packageTemplate.Execute(f, Tdata{EN: m_en, FR: m_fr})
}
