package main

import (
	"fmt"
	"os"
	"text/template"

	"regexp"

	"github.com/tbellembois/gochimitheque/global"
	"github.com/tbellembois/gochimitheque/locales"
)

// output file template
var packageTemplate = template.Must(template.New("").Delims("[[", "]]").Parse(`// Code generated by go generate; DO NOT EDIT.
script.
    [[ range $k, $v := .EN ]]
	var [[ $k ]] = "[[ $v ]]";
	[[ end ]]
    [[ range $k, $v := .FR ]]
	var [[ $k ]] = "[[ $v ]]";
	[[ end ]]
`))

// locales regexp
var r = regexp.MustCompile("\\[(\\S+)\\]\\n\\s+one = \"(.*)\"")

// locales map
var mEn map[string]string
var mFr map[string]string

// Tdata contains the "variable name" -> "translation string"
// maps for each supported language
type Tdata struct {
	EN map[string]string
	FR map[string]string
}

func main() {
	mEn = make(map[string]string)
	mFr = make(map[string]string)

	// finding matches
	msEn := r.FindAllStringSubmatch(string(locales.LOCALES_EN), -1)
	for _, v := range msEn {
		//fmt.Printf("%d. %s\n", k, v)
		//fmt.Printf("%s -> %s\n", v[1], v[2])
		k := fmt.Sprintf("locale_en_%s", v[1])
		mEn[k] = v[2]
	}
	msFr := r.FindAllStringSubmatch(string(locales.LOCALES_FR), -1)
	for _, v := range msFr {
		//fmt.Printf("%d. %s\n", k, v)
		//fmt.Printf("%s -> %s\n", v[1], v[2])
		k := fmt.Sprintf("locale_fr_%s", v[1])
		mFr[k] = v[2]
	}

	// opening output file
	f, err := os.Create("static/templates/localejs.jade")
	if err != nil {
		global.Log.Fatal(err)
	}
	defer f.Close()

	packageTemplate.Execute(f, Tdata{EN: mEn, FR: mFr})
}
